import { HandMode } from './constants';

const LEFT_HAND_KEYS = new Set(['q', 'w', 'e', 'r', 't', 'a', 's', 'd', 'f', 'g', 'z', 'x', 'c', 'v', 'b']);
const RIGHT_HAND_KEYS = new Set(['y', 'u', 'i', 'o', 'p', 'h', 'j', 'k', 'l', 'n', 'm']);

export type WordHand = 'left' | 'right' | 'mixed';

export function getWordHand(word: string): WordHand {
  const chars = word.toLowerCase().split('').filter(c => /[a-z]/.test(c));
  const leftCount = chars.filter(c => LEFT_HAND_KEYS.has(c)).length;
  const rightCount = chars.filter(c => RIGHT_HAND_KEYS.has(c)).length;

  if (leftCount > 0 && rightCount === 0) return 'left';
  if (rightCount > 0 && leftCount === 0) return 'right';
  return 'mixed';
}

const ALL_WORDS = [
  'abad', 'abadi', 'abai', 'abang', 'abar', 'abdi', 'abel', 'abnormal', 'absen', 'abses',
  'absolut', 'abstrak', 'absurd', 'abu', 'abuh', 'acak', 'acar', 'acara', 'acu', 'acuh',
  'acung', 'ada', 'adalah', 'adang', 'adanya', 'adat', 'adapun', 'adik', 'adil', 'aduh',
  'aduk', 'agar', 'agen', 'agung', 'agama', 'ahli', 'air', 'ajar', 'ajak', 'akhir',
  'akibat', 'akrab', 'aksi', 'aktif', 'aktivitas', 'aku', 'akun', 'akur', 'akurat', 'akut',
  'alam', 'alamat', 'alami', 'alang', 'alasan', 'alas', 'alat', 'album', 'alfabet', 'alhasil',
  'alih', 'aliran', 'almari', 'almarhum', 'alpa', 'altar', 'alternatif', 'alumni', 'alur',
  'aman', 'amanah', 'amat', 'amatir', 'ambang', 'ambil', 'ambisi', 'ambruk', 'ambulan',
  'amin', 'ampuh', 'ampun', 'anak', 'ancam', 'ancang', 'andai', 'andal', 'aneh', 'aneka',
  'anggap', 'anggota', 'anggrek', 'anggur', 'angin', 'angka', 'angkat', 'angkatan', 'angkut',
  'angsa', 'angsur', 'antar', 'antara', 'antena', 'anti', 'antik', 'antri', 'antusias',
  'anugerah', 'apa', 'apabila', 'apakah', 'aparat', 'api', 'apik', 'apit', 'aplikasi',
  'arab', 'arah', 'arak', 'arang', 'arahan', 'arca', 'area', 'arena', 'argumen', 'ari',
  'arifin', 'arisan', 'arogan', 'aroma', 'arti', 'artikel', 'artis', 'arung', 'arus',
  'asah', 'asam', 'asap', 'asar', 'asas', 'aset', 'asi', 'asing', 'asli', 'asma',
  'aspal', 'aspek', 'asrama', 'asri', 'asuransi', 'asuh', 'atas', 'atasan', 'atap', 'atau',
  'atlas', 'atlet', 'atom', 'atur', 'audit', 'aula', 'aura', 'awal', 'awam', 'awan',
  'awas', 'awet', 'ayah', 'ayam', 'ayang', 'ayat', 'ayun', 'azab', 'bab', 'babad',
  'babak', 'babat', 'babi', 'babon', 'babu', 'baca', 'bacaan', 'bacok', 'badan', 'badai',
  'badak', 'badut', 'bagai', 'bagaimana', 'bagan', 'bagas', 'bagasi', 'bagi', 'bagian',
  'bagus', 'bahan', 'bahas', 'bahasa', 'bahaya', 'bahkan', 'bahtera', 'bahwa', 'baik',
  'bait', 'baja', 'bajak', 'baji', 'baju', 'bak', 'bakal', 'bakar', 'bakaran', 'bakat',
  'bakau', 'baki', 'bakso', 'bakteri', 'bakti', 'baku', 'balai', 'balap', 'balas', 'balasan',
  'balik', 'balkon', 'balok', 'balon', 'balsam', 'balu', 'balut', 'bambu', 'ban', 'banal',
  'banci', 'bandar', 'bandara', 'bandel', 'banding', 'bandit', 'bandung', 'bandrol', 'bang',
  'banga', 'bangau', 'bangga', 'bangkit', 'bangkrut', 'bangku', 'bangsa', 'bangsawan', 'bangun',
  'bangunan', 'banjir', 'bank', 'bansos', 'bantu', 'bantuan', 'banyak', 'bapak', 'baptis',
  'bara', 'barang', 'barat', 'baret', 'baris', 'barisan', 'barter', 'baru', 'basa', 'basah',
  'basi', 'basis', 'baskara', 'basket', 'baskom', 'basmi', 'bata', 'batal', 'batang',
  'batas', 'batik', 'batin', 'batok', 'batu', 'batuk', 'bau', 'baut', 'bawa', 'bawaan',
  'bawah', 'bawang', 'bayam', 'bayangan', 'bayar', 'bayaran', 'bayi', 'bazar', 'bazoka',
  'beasiswa', 'bebas', 'bebek', 'beberapa', 'becak', 'beda', 'bedah', 'bedak', 'bedil',
  'begal', 'begini', 'begitu', 'bego', 'bejat', 'bekal', 'bekas', 'beku', 'bel', 'bela',
  'belahan', 'belajar', 'belakang', 'belanak', 'belanja', 'belas', 'belasungkawa', 'beli',
  'belimbing', 'belit', 'belok', 'belo', 'belum', 'belut', 'benah', 'benak', 'benang',
  'benar', 'bencana', 'benci', 'bendahara', 'bendera', 'bendung', 'bengek', 'bengkak',
  'bengkel', 'bengkok', 'bening', 'benjol', 'bentang', 'bentar', 'bentengan', 'bentuk',
  'bentukan', 'bentur', 'benar', 'beo', 'berada', 'berahi', 'beranda', 'beraneka', 'berani',
  'berantas', 'berapa', 'beras', 'berat', 'berawan', 'berbagai', 'berbahasa', 'berbakat',
  'berbatas', 'berbau', 'berbeda', 'berbicara', 'berbisik', 'berbuah', 'berbuat', 'berburu',
  'bercak', 'bercanda', 'bercinta', 'berdakwah', 'berdasar', 'berdebat', 'berdesa', 'berdiri',
  'berdoa', 'berdua', 'berduka', 'berfikir', 'bergabung', 'berganti', 'bergaul', 'bergaya',
  'bergema', 'bergerak', 'bergeser', 'bergizi', 'berguna', 'bergunung', 'berharap', 'berharga',
  'berhati', 'berhenti', 'berhitung', 'berhubung', 'beri', 'beria', 'berikut', 'beriman',
  'berin', 'beringas', 'berisik', 'berita', 'berjaga', 'berjalan', 'berjanji', 'berjaya',
  'berjelaga', 'berjemur', 'berjuang', 'berjudi', 'berjumpa', 'berkas', 'berkat', 'berkati',
  'berkecil', 'berkehendak', 'berkelas', 'berkelahi', 'berkemas', 'berkembang', 'berkenan',
  'berkepala', 'berkesan', 'berkibar', 'berkicau', 'berkiprah', 'berkisah', 'berkomunikasi',
  'berkomentar', 'berkumpul', 'berkunjung', 'berkurang', 'berkutat', 'berlabuh', 'berlaga',
  'berlainan', 'berlaku', 'berlangsung', 'berlari', 'berlatar', 'berlebihan', 'berlengan',
  'berlian', 'berlibur', 'berlindung', 'berliur', 'berlomba', 'bermain', 'bermanfaat',
  'bermaksud', 'bermalam', 'bermata', 'bermental', 'bermerk', 'bermimpi', 'berminat',
  'bermoral', 'bermotif', 'bermuara', 'bermuatan', 'bermusuhan', 'bernama', 'bernafas',
  'bernasib', 'berniat', 'bernilai', 'bernyanyi', 'berobat', 'berpacu', 'berpadu', 'berpagar',
  'berpakaian', 'berpaling', 'berpanas', 'berpapasan', 'berpedoman', 'berpeluk', 'berpengalaman',
  'berpengaruh', 'berpesta', 'berpetuah', 'berpikir', 'berpihak', 'berpindah', 'berpola',
  'berpotensi', 'berprasangka', 'berprestasi', 'berpuasa', 'berputar', 'bersamaan', 'bersabar',
  'bersaing', 'bersalah', 'bersama', 'bersatu', 'bersedia', 'berselang', 'bersenang',
  'berseri', 'berseru', 'bersih', 'bersikap', 'bersinar', 'bersiul', 'bersorak', 'bersumber',
  'bersumpah', 'bertaburan', 'bertahan', 'bertahap', 'bertajuk', 'bertalian', 'bertambah',
  'bertanding', 'bertanya', 'bertaruh', 'bertautan', 'berteduh', 'bertekad', 'bertekanan',
  'bertele', 'berteman', 'bertemu', 'bertengkar', 'berteriak', 'bertikai', 'bertindak',
  'bertingkat', 'bertiup', 'bertolak', 'bertubi', 'bertugas', 'bertujuan', 'bertumbuh',
  'bertumpuk', 'beruang', 'berubah', 'berujung', 'berulang', 'berumur', 'berunding', 'beruntung',
  'berurusan', 'berusia', 'berusaha', 'berwarna', 'berwujud', 'besar', 'besi', 'besok',
  'beta', 'betah', 'beton', 'betul', 'biar', 'biara', 'biasa', 'biasanya', 'biaya', 'bibir',
  'bibit', 'bicara', 'bidadari', 'bidang', 'bidik', 'biduan', 'bijak', 'biji', 'biksu',
  'bilah', 'bilang', 'bilas', 'bilik', 'bimbang', 'bimbing', 'bin', 'bina', 'binar', 'binasa',
  'binatang', 'bincang', 'bingkah', 'bingkai', 'bingung', 'bintang', 'bintik', 'bio', 'biola',
  'biologi', 'bioskop', 'birama', 'biro', 'birokrasi', 'biru', 'bis', 'bisa', 'bisik',
  'bisnis', 'bisu', 'bisul', 'blak', 'blangko', 'blankon', 'bledek', 'blender', 'blok',
  'blog', 'blokir', 'bobol', 'bobot', 'bocah', 'bocor', 'bodoh', 'bohong', 'boikot', 'bok',
  'bola', 'bolak', 'boleh', 'bolong', 'bom', 'bomba', 'bon', 'boneka', 'bongkar', 'bongkok',
  'bonjol', 'bonus', 'bopeng', 'bor', 'bordir', 'boro', 'boros', 'borong', 'borsi', 'botak',
  'botol', 'boyong', 'brahmana', 'brakat', 'brantas', 'brem', 'brengsek', 'briket', 'brilian',
  'brosur', 'brutal', 'buah', 'buahan', 'buai', 'buak', 'bual', 'buang', 'buas', 'buat',
  'buatan', 'buaya', 'bubar', 'bubuk', 'bubur', 'bubut', 'budak', 'budaya', 'budi', 'budidaya',
  'budiman', 'buga', 'bugar', 'buih', 'bujang', 'bujuk', 'bujur', 'buka', 'bukan', 'bukit',
  'bukti', 'buku', 'buldoser', 'buletin', 'bulet', 'bulu', 'buluh', 'buluk', 'bulut', 'bumbu',
  'bumi', 'buncis', 'buncit', 'bundel', 'bunduk', 'bunga', 'bungkam', 'bungker', 'bungkuk',
  'bungkus', 'bunglon', 'bunian', 'buntal', 'buntang', 'buntar', 'buntat', 'buntung', 'buntut',
  'bunuh', 'bunyi', 'bupati', 'buras', 'buras', 'buram', 'bursa', 'buru', 'buruan', 'buruh',
  'buruk', 'burung', 'busa', 'busana', 'busuk', 'busung', 'busur', 'buta', 'butek', 'butir',
  'butuh', 'butut', 'buwah', 'buzzer', 'cabai', 'cabang', 'cabik', 'cabul', 'cabut', 'cacah',
  'cacak', 'cacar', 'cacat', 'cadang', 'cadangan', 'cadar', 'cadas', 'cadel', 'cagar', 'cahaya',
  'cairan', 'cakap', 'cakar', 'cakep', 'cakram', 'cakrawala', 'cakup', 'cala', 'calon', 'calut',
  'cama', 'cambuk', 'camel', 'campur', 'campuran', 'candu', 'canggih', 'cangkir', 'cangkok',
  'cangkul', 'cantik', 'cantum', 'cap', 'capai', 'capek', 'capit', 'cara', 'cari', 'carikan',
  'carik', 'casing', 'cat', 'catat', 'catatan', 'catu', 'catur', 'cawang', 'cawan', 'cawat',
  'cebur', 'cecak', 'cedal', 'cedera', 'cegah', 'cegat', 'cek', 'cekal', 'cekam', 'cekatan',
  'cekcok', 'cekcot', 'ceking', 'cekung', 'celah', 'celaka', 'celana', 'celas', 'celup', 'celurit',
  'cemara', 'cemas', 'cemburu', 'cemerlang', 'cengang', 'cengir', 'cengkeram', 'centang', 'cepat',
  'ceper', 'ceplas', 'cerah', 'ceraka', 'ceramah', 'cerana', 'cerdas', 'cerdik', 'ceria', 'cerita',
  'cermin', 'cerna', 'ceroboh', 'ceruk', 'cesar', 'cetak', 'cetera', 'cetus', 'cibir', 'cicak',
  'cicil', 'cicip', 'cicit', 'cikal', 'cikrak', 'cikut', 'cina', 'cincin', 'cinta', 'ciok',
  'cipta', 'ciptaan', 'ciri', 'cirik', 'cita', 'citacita', 'cium', 'ciutkan', 'coba', 'cobal',
  'cocok', 'cocol', 'cogah', 'cokelat', 'cokol', 'colak', 'colek', 'coleng', 'comel', 'comot',
  'condong', 'congak', 'congek', 'congkel', 'contek', 'conteng', 'contoh', 'copet', 'copot',
  'corak', 'coreng', 'coret', 'corong', 'cowok', 'cuaca', 'cubit', 'cublak', 'cucak', 'cuci',
  'cucu', 'cucuk', 'cucur', 'cugat', 'cuit', 'cuka', 'cukong', 'cukup', 'cukur', 'cula', 'culik',
  'culun', 'cuma', 'cuman', 'cumi', 'cumplung', 'cungkil', 'cupang', 'cupet', 'cuping', 'cuplik',
  'curai', 'curam', 'curang', 'curat', 'curi', 'curut', 'dada', 'dadak', 'dadu', 'daerah',
  'daftar', 'daga', 'dagangan', 'daging', 'dahaga', 'dahan', 'dahsyat', 'dahulu', 'daif', 'daki',
  'dalam', 'dalang', 'dalil', 'daluarsa', 'damai', 'damar', 'damba', 'dambaan', 'dampak', 'damping',
  'dan', 'dana', 'danau', 'dandan', 'dangkal', 'dangkung', 'dapat', 'dapur', 'dara', 'darab',
  'darah', 'darat', 'dari', 'darma', 'darurat', 'dasar', 'data', 'datang', 'datar', 'datu',
  'datuk', 'daud', 'daun', 'daya', 'dayung', 'debat', 'debet', 'debit', 'debut', 'dedak',
  'dede', 'defilasi', 'degup', 'dek', 'dekap', 'dekat', 'deklarasi', 'deko', 'dekorasi', 'delta',
  'deman', 'demam', 'demi', 'demikian', 'demit', 'demo', 'demokrasi', 'demonstran', 'dengam',
  'dengan', 'dengar', 'dengki', 'dengkul', 'denger', 'dengkur', 'dengungan', 'denyut', 'depa',
  'depan', 'deposit', 'depot', 'depresi', 'deras', 'derau', 'deret', 'deretan', 'derik', 'dering',
  'derita', 'dermaga', 'deru', 'desa', 'desah', 'desain', 'desas', 'desember', 'desir', 'detai',
  'detail', 'detek', 'detensi', 'detik', 'deva', 'dewa', 'dewasa', 'dewi', 'dia', 'diagram',
  'dialek', 'dialog', 'diam', 'diameter', 'diare', 'didih', 'didik', 'diesel', 'diet', 'diferensial',
  'digital', 'diit', 'dikira', 'diktator', 'dilema', 'dimensi', 'din', 'dinas', 'dinasti', 'dinding',
  'dingin', 'dini', 'dinosaurus', 'diploma', 'diplomat', 'direktur', 'diri', 'dirikan', 'dis',
  'disangka', 'disebut', 'disiplin', 'disk', 'diskusi', 'disko', 'diskon', 'distribusi', 'ditulis',
  'diva', 'divisi', 'do', 'dobel', 'dobi', 'dobol', 'doa', 'dodol', 'dodot', 'dogma', 'dok',
  'dokar', 'dokok', 'doktor', 'dokter', 'dokumentasi', 'dokumen', 'dolar', 'dolanan', 'dolog',
  'domain', 'domba', 'domes', 'domestik', 'domino', 'dompet', 'donasi', 'donat', 'dongak',
  'dongeng', 'dongkol', 'dongkrak', 'donor', 'doping', 'dorong', 'dosa', 'dosen', 'dosis',
  'dot', 'doyong', 'drama', 'drastis', 'drum', 'du', 'dua', 'dualisme', 'dubes', 'dubur',
  'duda', 'duduk', 'dudukan', 'duga', 'dugaan', 'duka', 'dukacita', 'dukuh', 'dukun', 'dukung',
  'dukungan', 'dulu', 'duman', 'dun', 'dunia', 'duniawi', 'duo', 'dupa', 'dupak', 'duplikat',
  'dura', 'duri', 'durian', 'dursila', 'dusta', 'dusun', 'duta', 'duyung', 'dwi', 'dzikir',
  'eboni', 'eceran', 'edar', 'edisi', 'editor', 'edukasi', 'efek', 'efektif', 'efisien', 'ego',
  'egois', 'ejaan', 'ejekan', 'ekitar', 'ekonomi', 'ekonomis', 'ekosistem', 'eksklusif', 'ekspansi',
  'ekspedisi', 'eksperimen', 'ekspor', 'ekspresi', 'ekstensif', 'ekstra', 'ekultur', 'elastis',
  'elegan', 'elemen', 'elit', 'elok', 'elpiji', 'email', 'emas', 'embargo', 'emban', 'ember',
  'embrio', 'embus', 'emigran', 'emosi', 'empang', 'empat', 'empuk', 'empu', 'emulsi', 'enak',
  'enam', 'endap', 'energi', 'enggan', 'engkau', 'enigma', 'entah', 'enteng', 'entri', 'epidemi',
  'episode', 'era', 'erat', 'erek', 'ereksi', 'erosi', 'erotis', 'es', 'esa', 'esai', 'esens',
  'esensi', 'esok', 'estetika', 'estimasi', 'etik', 'etika', 'etis', 'etnis', 'etnografi', 'evaluasi',
  'evolusi', 'faedah', 'faham', 'fail', 'fajr', 'faktor', 'faktur', 'fakta', 'fakultas', 'falsafah',
  'familia', 'familiar', 'fan', 'fana', 'fantasi', 'fase', 'fashion', 'fasih', 'fasilitas', 'fatal',
  'fatamorgana', 'fauna', 'favorit', 'federal', 'federasi', 'feminisme', 'fenomena', 'feodal',
  'fermentasi', 'festival', 'figur', 'fikir', 'fiksi', 'filem', 'filial', 'film', 'filsafat',
  'filter', 'final', 'finansial', 'finisi', 'firma', 'firus', 'fisik', 'fisis', 'fitrah', 'fitnah',
  'fobia', 'fokus', 'fonem', 'fonetik', 'font', 'formasi', 'format', 'formula', 'formulir', 'forsa',
  'forum', 'fosfor', 'fosil', 'foto', 'fotokopi', 'foya', 'fragmen', 'fraksi', 'frasa', 'frekuensi',
  'front', 'frustrasi', 'fundamental', 'fungsi', 'fungsional', 'fusi', 'futsal', 'gabung', 'gabungan',
  'gadai', 'gadang', 'gading', 'gadis', 'gaduh', 'gadung', 'gagah', 'gagak', 'gagal', 'gagap',
  'gagas', 'gagasan', 'gagu', 'gairah', 'gaji', 'galak', 'galang', 'galeri', 'gali', 'galian',
  'galih', 'gam', 'gama', 'gamang', 'gambar', 'gambaran', 'gambit', 'gambut', 'gamelan', 'gampang',
  'gancu', 'ganda', 'gandeng', 'gandum', 'gang', 'ganggu', 'gangguan', 'ganjal', 'ganjil', 'ganti',
  'gantung', 'gantungan', 'gapai', 'gara', 'garang', 'garansi', 'garasi', 'gardu', 'garis', 'garpu',
  'garuk', 'gas', 'gasal', 'gatal', 'gaung', 'gaur', 'gawai', 'gawang', 'gawat', 'gaya', 'gayung',
  'gebrak', 'gebu', 'gebuk', 'gedang', 'gedung', 'gegar', 'gegap', 'gejala', 'gejolak', 'geladak',
  'gelak', 'gelang', 'gelap', 'gelar', 'gelas', 'gelatik', 'gelembung', 'geleng', 'geliga', 'geliat',
  'geligi', 'gelimang', 'gelincir', 'geling', 'gelisah', 'gelitik', 'gelobang', 'gelombang', 'gelora',
  'gema', 'gemas', 'gembala', 'gembira', 'gembung', 'gembok', 'gembos', 'gembur', 'gemetar', 'geming',
  'gempita', 'gemuk', 'gemuruh', 'genap', 'gencatan', 'gendang', 'gendong', 'gendut', 'generasi',
  'genetik', 'gengam', 'genggam', 'gengsi', 'genius', 'genjot', 'gentar', 'genting', 'geografi',
  'geometri', 'geopolitik', 'gerak', 'gerakan', 'gerangan', 'gerayang', 'gerbang', 'gerbong',
  'gereja', 'gerenjeng', 'geretak', 'gergaji', 'gerha', 'gerhana', 'gerilya', 'gering', 'geris',
  'gerisik', 'gerobak', 'gerombolan', 'gerudi', 'geruh', 'geruk', 'gerung', 'gerus', 'geser',
  'gesit', 'getar', 'getaran', 'getir', 'getol', 'giatan', 'gigi', 'gigih', 'gigit', 'gila', 'gilang',
  'gilap', 'gilas', 'gilir', 'giling', 'gima', 'gin', 'gincu', 'ginjal', 'gir', 'giro', 'gitar',
  'gitu', 'gizi', 'glamor', 'global', 'globalisasi', 'goa', 'goceng', 'godaan', 'goda', 'gol',
  'golek', 'golf', 'golong', 'golongan', 'gombak', 'gombalan', 'goncang', 'gondol', 'gong', 'gonggang',
  'gonggong', 'gonjang', 'gopoh', 'gorengan', 'goreng', 'gores', 'gorok', 'gosip', 'gosok', 'gotong',
  'goyang', 'grafik', 'gram', 'grama', 'granat', 'gratis', 'greget', 'gresik', 'griya', 'gua',
  'gubah', 'gubang', 'gubuk', 'gudang', 'gudu', 'gugah', 'gugat', 'gugup', 'gugur', 'gugusan',
  'gula', 'gulai', 'gulat', 'guling', 'gulir', 'gulung', 'guna', 'gunakan', 'guncang', 'gundah',
  'gundul', 'gunem', 'guni', 'gunting', 'guntur', 'gunung', 'gurah', 'gurami', 'gurita', 'gurih',
  'gurinda', 'gurindam', 'guru', 'guruh', 'gusar', 'gusi', 'gusuran', 'habis', 'habitat', 'hadap',
  'hadiah', 'hadir', 'hadirin', 'hafal', 'hai', 'haid', 'haji', 'hajat', 'hak', 'hakim', 'hakikat',
  'hal', 'halal', 'halaman', 'halang', 'halangan', 'halau', 'halia', 'halimun', 'halo', 'halte',
  'haluan', 'halus', 'ham', 'hambar', 'hambat', 'hambatan', 'hamba', 'hamburger', 'hamil', 'hampa',
  'hamparan', 'hampir', 'hamus', 'hancur', 'handai', 'handuk', 'hangat', 'hangar', 'hangus', 'hantam',
  'hantar', 'hantu', 'hanya', 'hanyut', 'hapus', 'harap', 'harapan', 'harga', 'harian', 'hari',
  'harimau', 'harmoni', 'harmonika', 'harpa', 'harta', 'harum', 'harus', 'hasil', 'hasilkan',
  'hasrat', 'hasut', 'hati', 'hatihati', 'haus', 'hawa', 'hawatir', 'hayat', 'hebat', 'heboh',
  'hegemoni', 'hegemon', 'hektar', 'helikopter', 'hemat', 'hembus', 'hendak', 'hening', 'heran',
  'heroin', 'hewan', 'hiasan', 'hibah', 'hibur', 'hiburan', 'hidangan', 'hidayah', 'hidung', 'hidup',
  'hidrolik', 'hierarki', 'hijab', 'hijau', 'hijrah', 'hikayat', 'hikmah', 'hilang', 'himalaya',
  'hina', 'hindar', 'hindari', 'hindu', 'hingga', 'hipertensi', 'hipnotis', 'hipotesis', 'hirap',
  'hirup', 'hisab', 'hisap', 'historis', 'hitam', 'hitung', 'hiu', 'hobi', 'hokky', 'honor',
  'hore', 'horizontal', 'hormat', 'hormati', 'hormon', 'hotel', 'hubung', 'hubungan', 'hujam',
  'hujan', 'hujat', 'hujung', 'hukum', 'hukuman', 'hulu', 'huma', 'humanis', 'humor', 'huni',
  'hunjam', 'hunus', 'huruf', 'huru', 'hutan', 'hutang', 'iba', 'ibadah', 'ibar', 'ibadat',
  'ibarat', 'ibu', 'ibukota', 'ibunda', 'identifikasi', 'ide', 'ideal', 'identik', 'identitas',
  'ideologi', 'idiom', 'idola', 'igau', 'ijab', 'ijazah', 'ijin', 'ijuk', 'ikan', 'ikat', 'ikatan',
  'ikhtiar', 'ikhlas', 'iklim', 'ikon', 'ikrar', 'ikut', 'ikutan', 'ilahi', 'ilalang', 'ilham',
  'ilmu', 'ilmiah', 'ilmuwan', 'ilustrasi', 'imam', 'iman', 'imbangi', 'imbang', 'imbas', 'imbau',
  'iming', 'imigran', 'imigrasi', 'imlek', 'impas', 'impian', 'implikasi', 'implisit', 'impor',
  'impotensi', 'imun', 'imunisasi', 'inang', 'incar', 'indah', 'indeks', 'indera', 'indikasi',
  'indikator', 'individu', 'indonesia', 'induk', 'indung', 'industri', 'inersia', 'infak', 'infeksi',
  'inferior', 'inflasi', 'info', 'informal', 'informasi', 'infrastruktur', 'ingat', 'ingatan',
  'ingin', 'inggris', 'ini', 'inisiatif', 'injak', 'injeksi', 'injil', 'inkonsisten', 'inovasi',
  'inovatif', 'input', 'insaf', 'insan', 'insang', 'insiden', 'insentif', 'insinyur', 'inspirasi',
  'instalasi', 'instan', 'instansi', 'institusi', 'instruksi', 'instrumen', 'intan', 'integrasi',
  'intelektual', 'intelek', 'intelijensi', 'intelijen', 'intensif', 'intensitas', 'interaksi',
  'interior', 'internal', 'internasional', 'internet', 'interpretasi', 'interupsi', 'interval',
  'interviu', 'inti', 'intim', 'intimidasi', 'intip', 'introspeksi', 'intuisi', 'inventaris',
  'investasi', 'investor', 'ion', 'ipar', 'irama', 'irasional', 'iri', 'irigasi', 'iring', 'iris',
  'irisan', 'ironi', 'isbat', 'isi', 'iseng', 'isikan', 'islam', 'isolasi', 'istana', 'isteri',
  'istiadat', 'istilah', 'istimewa', 'istirahat', 'istri', 'isyarat', 'itu', 'iuran', 'izin',
  'jabar', 'jabat', 'jabatan', 'jadi', 'jadilah', 'jadwal', 'jaga', 'jagat', 'jagoan', 'jagung',
  'jahil', 'jahit', 'jahat', 'jail', 'jajan', 'jajak', 'jajanan', 'jajaran', 'jajah', 'jajal',
  'jaksa', 'jala', 'jalak', 'jalan', 'jalanan', 'jalang', 'jalani', 'jalankan', 'jalur', 'jam',
  'jaman', 'jamah', 'jamaah', 'jamak', 'jambak', 'jamban', 'jambang', 'jambi', 'jambore', 'jambu',
  'jambul', 'jamin', 'jaminan', 'jampi', 'jamuan', 'jamur', 'janda', 'jangan', 'jangka', 'jangkau',
  'jangkrik', 'jangkung', 'janji', 'jantan', 'jantung', 'januari', 'jarak', 'jarang', 'jari',
  'jaring', 'jaringan', 'jarum', 'jas', 'jasa', 'jasad', 'jasmani', 'jatah', 'jati', 'jatim',
  'jatuh', 'jauh', 'jauhi', 'jawab', 'jawaban', 'jawan', 'jawara', 'jaya', 'jazz', 'jebak',
  'jebakan', 'jebol', 'jeda', 'jegal', 'jelajah', 'jelang', 'jelas', 'jelaskan', 'jelata', 'jelek',
  'jeli', 'jelita', 'jelmaan', 'jema', 'jemaat', 'jemari', 'jembatan', 'jemput', 'jemur', 'jenaka',
  'jenak', 'jenazah', 'jendela', 'jenderal', 'jengkel', 'jenguk', 'jenis', 'jenuh', 'jepang',
  'jepit', 'jepret', 'jera', 'jerah', 'jerami', 'jerang', 'jerat', 'jeratan', 'jerawat', 'jerih',
  'jering', 'jerit', 'jeritan', 'jernih', 'jero', 'jeroan', 'jeruk', 'jeruji', 'jerumat', 'jerung',
  'jidat', 'jijik', 'jika', 'jilat', 'jilbab', 'jilid', 'jin', 'jinak', 'jingga', 'jinjing', 'jinjit',
  'jiwa', 'jiwanya', 'jodoh', 'joget', 'joki', 'jolok', 'jongkok', 'jorok', 'jubah', 'jual', 'jualan',
  'juang', 'juara', 'jubel', 'judes', 'judi', 'judika', 'judo', 'judul', 'juga', 'jugal', 'jugun',
  'jujur', 'jukung', 'juli', 'juluk', 'julukan', 'julung', 'jumantara', 'jumat', 'jumlah', 'jumpa',
  'jumpai', 'jumput', 'jun', 'junani', 'jung', 'jungkat', 'jungkir', 'juni', 'junior', 'junjung',
  'junkfood', 'junub', 'jurai', 'jurang', 'juri', 'jurnal', 'jurnalis', 'juru', 'jurusan', 'jurus',
  'jus', 'justru', 'juta', 'jutaan', 'kabel', 'kabar', 'kabaret', 'kabat', 'kabinet', 'kabir',
  'kabul', 'kabung', 'kabupaten', 'kabur', 'kabut', 'kaca', 'kacamata', 'kacang', 'kacau', 'kacung',
  'kadal', 'kadar', 'kadaster', 'kadim', 'kado', 'kafe', 'kafein', 'kafir', 'kaget', 'kagok', 'kagum',
  'kai', 'kail', 'kain', 'kaisar', 'kait', 'kaitan', 'kaji', 'kajian', 'kakak', 'kakaktua', 'kakao',
  'kakap', 'kakas', 'kakek', 'kaki', 'kakus', 'kalah', 'kalai', 'kalamari', 'kalang', 'kalangar',
  'kalau', 'kaldron', 'kaldu', 'kalender', 'kali', 'kalian', 'kaliber', 'kalibrasi', 'kalijaga',
  'kalimat', 'kalis', 'kalkulasi', 'kalkulatur', 'kalori', 'kalung', 'kalut', 'kamar', 'kambing',
  'kamboja', 'kambuh', 'kamera', 'kami', 'kamis', 'kampanye', 'kampret', 'kampung', 'kampus', 'kamu',
  'kamus', 'kana', 'kanak', 'kanan', 'kancah', 'kancing', 'kancur', 'kanda', 'kandang', 'kandas',
  'kandidat', 'kandung', 'kandungan', 'kangkung', 'kangen', 'kanjeng', 'kanker', 'kanon', 'kantong',
  'kantor', 'kantuk', 'kanvas', 'kapal', 'kapak', 'kapan', 'kapas', 'kapasitas', 'kaper', 'kaporit',
  'kapsul', 'kapten', 'kaptol', 'kapur', 'karabin', 'karak', 'karakter', 'karang', 'karangan', 'karantina',
  'karap', 'karaoke', 'karat', 'karbit', 'karbol', 'kardinal', 'kardus', 'karena', 'karet', 'kargo',
  'karib', 'karibu', 'karier', 'karikatur', 'karis', 'karisma', 'karma', 'karnaval', 'karnivor',
  'karoseri', 'karper', 'karsa', 'kartika', 'karton', 'kartu', 'kartun', 'kartunis', 'karun', 'karung',
  'karunia', 'karut', 'karya', 'karyawan', 'kasar', 'kasasi', 'kasat', 'kasau', 'kaseh', 'kasem',
  'kaset', 'kasi', 'kasian', 'kasih', 'kasino', 'kasir', 'kastel', 'kastil', 'kasturi', 'kasus',
  'kasut', 'kata', 'katak', 'katakan', 'katalog', 'katam', 'katarak', 'kategori', 'kater', 'kati',
  'katib', 'katil', 'katimumul', 'kation', 'katrol', 'katuk', 'katup', 'kaum', 'kaur', 'kaus', 'kaus',
  'kautsar', 'kaveling', 'kawah', 'kawai', 'kawal', 'kawalan', 'kawan', 'kawanan', 'kawasan', 'kawat',
  'kawin', 'kaya', 'kayak', 'kayu', 'keadaan', 'keadilan', 'keahlian', 'keajaiban', 'keakraban',
  'kealamiah', 'keamanan', 'keampuhan', 'keanekaragaman', 'keangkuhan', 'kearifan', 'keaslian',
  'keasyikan', 'keawetan', 'kebab', 'kebakaran', 'kebal', 'kebangkitan', 'kebangsaan', 'kebanggaan',
  'kebanyakan', 'kebarat', 'kebaikan', 'kebahagiaan', 'kebasahan', 'kebaya', 'kebejatan', 'keberangkatan',
  'keberanian', 'keberatan', 'keberhasilan', 'keberkahan', 'kebersihan', 'keberuntungan', 'kebetuluan',
  'kebiasaan', 'kebijakan', 'kebijaksanaan', 'kebingungan', 'kebiri', 'kebodohan', 'kebohongan',
  'kebon', 'kebosanan', 'kebudayaan', 'kebugaran', 'kebulatan', 'kebun', 'kebuntuan', 'kebutuhan',
  'kecam', 'kecamatan', 'kecanduan', 'kecantikan', 'kecap', 'kecar', 'kecapaian', 'kecapi', 'kecebong',
  'kecederaan', 'kecel', 'kecelakaan', 'kecemasan', 'kecemburuan', 'kecendekiaan', 'kecenderungan',
  'kecepatan', 'kecerdasan', 'keceriaan', 'kecermatan', 'kecewa', 'kecewaan', 'kecil', 'kecimpung',
  'kecipak', 'kecoak', 'kecoh', 'kecokelatan', 'kecongkakan', 'kecuali', 'kecubit', 'kecurigaan',
  'kecurangan', 'kecutut', 'kedaerahan', 'kedahsyatan', 'kedai', 'kedamaian', 'kedang', 'kedap',
  'kedatangan', 'kedaulatan', 'kedekatan', 'kedengarannya', 'kedewasaan', 'kedip', 'kedisiplinan',
  'kedok', 'kedokteran', 'kedondong', 'kedua', 'keduanya', 'kedudukan', 'kedukaan', 'kedutaan',
  'keeksotisan', 'kefanaan', 'kegaduhan', 'kegagalan', 'kegairahan', 'kegamangan', 'keganasan',
  'keganjilan', 'kegarangan', 'kegemaran', 'kegembiraan', 'kegenitan', 'kegerahan', 'kegetiran',
  'kegiatan', 'kegigihan', 'kegirangan', 'kegoncangan', 'keguguran', 'kegunaan', 'kehancuran',
  'kehandalan', 'kehangatan', 'kehebatan', 'kehendak', 'keheningan', 'kehidupan', 'kehilangan',
  'kehinaan', 'kehormatan', 'keibuan', 'keihlasan', 'keikutsertaan', 'keimanan', 'keindahan',
  'keinginan', 'keistimewaan', 'kejadian', 'kejahataan', 'kejam', 'kejang', 'kejar', 'kejarlah',
  'kejatuhan', 'kejayaan', 'kejelekan', 'kejelian', 'kejengkelan', 'kejernihan', 'keji', 'kejijikan',
  'keju', 'kejujuran', 'kejumudan', 'kejur', 'kejuruan', 'kejut', 'kejutan', 'kekacauan', 'kekagetan',
  'kekaguman', 'kekaisaran', 'kekal', 'kekang', 'kekasih', 'kekayaan', 'kekecewaan', 'kekejaman',
  'kekejangan', 'kekejian', 'kekeliruan', 'kekenyangan', 'kekentalan', 'kekerasan', 'kekhawatiran',
  'kekuasaan', 'kekuatan', 'kekurangan', 'kelabang', 'keladi', 'kelahi', 'kelahiran', 'kelak',
  'kelalaian', 'kelam', 'kelamaan', 'kelamaan', 'kelamin', 'kelana', 'kelancaran', 'kelangkaan',
  'kelanjutan', 'kelapa', 'kelar', 'kelari', 'kelas', 'kelasi', 'kelat', 'kelautan', 'kelawar',
  'kelayakan', 'kelebihan', 'kelembaban', 'kelembagaan', 'kelembutan', 'kelemumur', 'kelengahan',
  'kelengkapan', 'kelenjar', 'kelepasan', 'kelereng', 'kelelahan', 'keleluasaan', 'kelewatan',
  'kelezatan', 'keli', 'kelicikan', 'kelih', 'keliling', 'kelim', 'kelimpungan', 'kelincahan',
  'kelinci', 'kelindan', 'kelingking', 'kelip', 'keliru', 'kelit', 'kelok', 'kelola', 'kelom',
  'kelompok', 'kelonan', 'kelonggaran', 'kelopak', 'keluar', 'keluarga', 'keluarkan', 'keluasan',
  'keluguan', 'keluh', 'keluhan', 'keluhuran', 'keluk', 'kelulu', 'kelumpuhan', 'kelupaan', 'kelupas',
  'keluwesan', 'kemacetan', 'kemagnetan', 'kemah', 'kemahalan', 'kemahiran', 'kemajuan', 'kemakluman',
  'kemakmuran', 'kemampuan', 'kemanakah', 'kemandirian', 'kemanfaatan', 'kemanisan', 'kemanusiaan',
  'kemapanan', 'kemarin', 'kemas', 'kematangan', 'kematian', 'kemasan', 'kemau', 'kemayoran',
  'kembali', 'kembalian', 'kembang', 'kembangan', 'kembar', 'kemboja', 'kembung', 'kemeja', 'kemeling',
  'kemenakan', 'kemenangan', 'kemendikbud', 'kemenlu', 'kementerian', 'kemerdekaan', 'kemewahan',
  'kemiri', 'kemiskinan', 'kemo', 'kemoterapi', 'kempa', 'kempes', 'kempis', 'kemudi', 'kemudahan',
  'kemudian', 'kemul', 'kemuliaan', 'kemunafikan', 'kemunculan', 'kemundur', 'kemungkinan', 'kemurnian',
  'kemurungan', 'kena', 'kenai', 'kenal', 'kenalan', 'kenang', 'kenangan', 'kenapa', 'kenanglah',
  'kencang', 'kencing', 'kendala', 'kendang', 'kendara', 'kendaran', 'kendaraan', 'kendati', 'kendur',
  'kenegaraan', 'kenikmatan', 'keniscayaan', 'kenop', 'kenormalan', 'kentalkan', 'kenyang', 'kentang',
  'keok', 'kepahlawanan', 'kepada', 'kepahitan', 'kepak', 'kepal', 'kepala', 'kepalsuan', 'kepandaian',
  'kepangannya', 'kepanikan', 'kepanjangan', 'kepapaan', 'keparahan', 'keparat', 'kepariwisataan',
  'kepastian', 'kepatahannya', 'kepausan', 'kepayahan', 'kepedasan', 'kepedulian', 'kepekaan',
  'kepemilikan', 'kepemimpinan', 'kepenakan', 'kepenatan', 'kepencilan', 'kependekan', 'kependudukan',
  'kepengarangan', 'kepengecutan', 'kepentingan', 'kepenuh', 'kepenulisan', 'kepenyairan', 'keperakan',
  'keperawan', 'kepercayaan', 'kepergian', 'keperluan', 'keperluannya', 'kepertamaan', 'kepiawaian',
  'kepik', 'kepilu', 'kepincangan', 'kepingan', 'kepingin', 'kepintaran', 'kepiting', 'kepolisian',
  'keponakan', 'kepopuleran', 'keposisian', 'kepramukaan', 'keprihatinan', 'kepudaran', 'kepulauan',
  'kepulangannya', 'kepunahan', 'kepunyaan', 'kepura', 'kepuasan', 'keputusan', 'keputusasaan',
  'kera', 'kerabat', 'keracunan', 'keragaman', 'kerahasiaan', 'kerahkan', 'kerajinan', 'kerakyatan',
  'keram', 'keramaian', 'keramahan', 'keramat', 'keramik', 'keran', 'keranda', 'kerang', 'kerangka',
  'keranjang', 'keranjingan', 'kerap', 'keras', 'kerasan', 'kerat', 'kerawang', 'kerbau', 'kerdil',
  'kerek', 'kerelaan', 'keren', 'kerepotan', 'keretan', 'keretakan', 'keria', 'keributan', 'kerikil',
  'kerinduan', 'kering', 'keringet', 'keringging', 'keringkat', 'keringkasan', 'kerinting', 'kerja',
  'kerjaan', 'kerjakan', 'kerjasama', 'kerlap', 'kerlip', 'kermun', 'kerombongan', 'keroncong',
  'kerongkongan', 'keropeng', 'keropok', 'keropos', 'keroyokan', 'kerpus', 'kersan', 'kertas',
  'keruan', 'kerucut', 'keruh', 'kerukunan', 'kerumitan', 'kerumun', 'kerumunan', 'kerunyutan',
  'kerupuk', 'kerusakan', 'kerusuhan', 'kesabaran', 'kesah', 'kesaktian', 'kesaksian', 'kesal',
  'kesalahan', 'kesamaan', 'kesantunan', 'kesaran', 'kesarjanaan', 'kesatria', 'kesatuan', 'kesayangan',
  'kesederhanaan', 'kesediaan', 'kesedihan', 'keseimbangan', 'kesejahteraan', 'kesejukan', 'kesel',
  'kesela', 'keselamatan', 'keseluruhan', 'kesempatan', 'kesempitan', 'kesempurnaan', 'kesenangan',
  'kesendirian', 'kesengsaraan', 'keseninan', 'kesenjangan', 'kesepakatan', 'kesepian', 'keseriusan',
  'keseronokan', 'keseruan', 'kesetiaan', 'kesetaraan', 'kesewenangan', 'kesialan', 'kesiapan',
  'kesiapsiagaan', 'kesibukan', 'kesigapan', 'kesimpulan', 'kesinambungan', 'kesiswaan', 'kesit',
  'kesobongan', 'kesombongan', 'kesosialan', 'kesturi', 'kesuburan', 'kesucian', 'kesudahan',
  'kesukaan', 'kesukarelaan', 'kesukaran', 'kesuksesan', 'kesulitan', 'kesumba', 'kesungguhan',
  'kesunyian', 'kesuraman', 'kesusilaan', 'kesusahan', 'keswadayaan', 'ketabahan', 'ketahanan',
  'ketahui', 'ketajaman', 'ketakjuban', 'ketakutan', 'ketam', 'ketangguhan', 'ketangkasan',
  'ketapang', 'ketapel', 'ketat', 'ketawa', 'ketebalan', 'ketegangan', 'ketegasan', 'keteguhan',
  'ketekoran', 'ketela', 'ketelenan', 'ketemu', 'ketenagakerjaan', 'ketenangan', 'ketenaran',
  'ketentraman', 'ketentuan', 'ketepatan', 'keterampilan', 'keterangan', 'keteraniayaan',
  'keterbukaan', 'ketergantungan', 'ketergesaan', 'keterhambatan', 'keterikatan', 'keterlambatan',
  'keterlibatan', 'keterpurukan', 'ketersediaan', 'ketersingkapan', 'ketersingkiran', 'keterusan',
  'ketiak', 'ketiban', 'ketidakadilan', 'ketidakpastian', 'ketidaksempurnaan', 'ketidaktahuan',
  'ketiga', 'ketikaitu', 'ketikaitu', 'ketika', 'ketimun', 'ketinggalan', 'ketinggian', 'ketip',
  'ketipung', 'ketitik', 'ketlingsut', 'ketombe', 'ketoprak', 'ketrampilan', 'ketu', 'ketua',
  'ketuban', 'ketuk', 'ketukan', 'ketukang', 'ketumbar', 'ketumpulan', 'ketuntasan', 'keturunan',
  'ketut', 'keuangan', 'keuletan', 'keunggulan', 'keunikan', 'keuntungan', 'keutamaan', 'keutuhan',
  'kewajaran', 'kewajiban', 'kewarganegaraan', 'kewaspadaan', 'kewenangan', 'kewibawaan', 'kewirausahaan',
  'khaki', 'khalayak', 'khalifah', 'khamar', 'khamis', 'khaos', 'kharimatik', 'kharimasmatis', 'khas',
  'khasiat', 'khatam', 'khawatir', 'khayal', 'kheleksi', 'khianati', 'khidmat', 'khilaf', 'khitan',
  'khitbah', 'khotbah', 'khuldi', 'khusu', 'khusuk', 'khusus', 'kial', 'kiambang', 'kian', 'kias',
  'kiat', 'kibaran', 'kiblat', 'kibul', 'kicau', 'kidal', 'kidung', 'kijang', 'kikil', 'kikir',
  'kikisan', 'kikuk', 'kilah', 'kilang', 'kilap', 'kilar', 'kilat', 'kilau', 'kilo', 'kilogram',
  'kilometer', 'kim', 'kimia', 'kimpul', 'kina', 'kincir', 'kinerja', 'kini', 'kios', 'kip', 'kipas',
  'kiprah', 'kira', 'kiraan', 'kirab', 'kirai', 'kirap', 'kiras', 'kirat', 'kiranya', 'kiri', 'kirim',
  'kiriman', 'kirtya', 'kisah', 'kisar', 'kisaran', 'kisi', 'kismis', 'kisruh', 'kista', 'kit',
  'kita', 'kitab', 'kitar', 'kitaran', 'klaim', 'klambi', 'klamer', 'klan', 'klapa', 'klarifikasi',
  'klarinet', 'klasemen', 'klasifikasi', 'klasik', 'klausa', 'klaustrofobia', 'klausul', 'klaver',
  'klem', 'kleneng', 'klerek', 'klien', 'klik', 'klinik', 'klip', 'klise', 'kloaka', 'klop', 'klor',
  'kloso', 'klub', 'kluarga', 'kluwak', 'knek', 'kobaran', 'kobar', 'koboi', 'kocak', 'koci', 'kocok',
  'kode', 'kodek', 'kodok', 'koin', 'kokok', 'kokoh', 'kokong', 'kokoronjo', 'kolaborasi', 'kolak',
  'kolam', 'kolar', 'kolega', 'koleksi', 'kolektor', 'kolektif', 'kolem', 'koles', 'kolesterol',
  'kolik', 'kolom', 'kolone', 'kolonel', 'koloni', 'kolonial', 'kolong', 'komandan', 'komando',
  'komar', 'kombat', 'kombinasi', 'komedian', 'komedi', 'komentar', 'komentator', 'komersi',
  'komersial', 'komik', 'komisi', 'komit', 'komite', 'komitmen', 'komoditi', 'komodor', 'kompak',
  'kompas', 'kompatibel', 'kompensasi', 'kompeten', 'kompetensi', 'kompetisi', 'kompilasi', 'kompleks',
  'kompleksitas', 'komplet', 'komplikasi', 'kompol', 'komponen', 'komposer', 'komposter', 'komposisi',
  'komprehensif', 'kompresor', 'kompromi', 'komputer', 'komunal', 'komunikasi', 'komunis', 'komunitas',
  'konci', 'kondang', 'kondisi', 'kondisional', 'konduite', 'konduktor', 'koneksi', 'konfederasi',
  'konferensi', 'konfigurasi', 'konfirmasi', 'konflik', 'konfrontasi', 'kongko', 'kongkret',
  'kongres', 'konglomerat', 'koni', 'konjungsi', 'konkrit', 'konkuren', 'kono', 'konon', 'konotasi',
  'konret', 'konsen', 'konsensus', 'konsentrat', 'konsentrasi', 'konsep', 'konsepsi', 'konseptual',
  'konser', 'konsern', 'konservasi', 'konsesi', 'konsideran', 'konsinyasi', 'konsisten', 'konsistensi',
  'konsolidasi', 'konsonan', 'konsorsium', 'konspirasi', 'konstanta', 'konstitusi', 'konstruksi',
  'konstruktif', 'konsul', 'konsulat', 'konsultan', 'konsultasi', 'konsumen', 'konsumsi', 'konsumtif',
  'kontak', 'kontaminasi', 'konteks', 'kontemporer', 'kontes', 'kontinen', 'kontinental', 'kontingen',
  'kontinu', 'kontinuitas', 'kontol', 'kontra', 'kontradiksi', 'kontrak', 'kontraktor', 'kontraksi',
  'kontras', 'kontribusi', 'kontrol', 'kontroler', 'kontroversi', 'kontur', 'konveksi', 'konvensi',
  'konvergensi', 'konversi', 'konveyor', 'konyol', 'koor', 'kooperasi', 'kooperatif', 'koordinasi',
  'koordinat', 'koordinator', 'kop', 'koper', 'koperal', 'koperasi', 'kopi', 'kopiah', 'kopilot',
  'koplak', 'kopong', 'kopral', 'kopyor', 'koran', 'korannya', 'korban', 'kordi', 'korea', 'koreografi',
  'koridor', 'koripsi', 'kornet', 'koro', 'korosi', 'korporasi', 'korporat', 'korps', 'korsleting',
  'korupsi', 'koruptor', 'kosek', 'kosel', 'kosmetik', 'kosmik', 'kosmis', 'kosmos', 'kosong', 'kost',
  'kosta', 'kostum', 'kot', 'kota', 'kotak', 'kotamadya', 'koteka', 'kotor', 'kotoran', 'kover', 'krack',
  'krajan', 'krakatau', 'kram', 'krama', 'kramatan', 'kraton', 'krauk', 'kreasi', 'kreatif', 'kreativitas',
  'kreator', 'kredibel', 'kredibilitas', 'kredit', 'kreditur', 'kredo', 'krem', 'kremasi', 'kren',
  'kresek', 'krida', 'kriket', 'krim', 'kriminal', 'kriminalisasi', 'kriminologi', 'kring', 'kripik',
  'krisis', 'kristal', 'kristalisasi', 'kristen', 'kristus', 'kriteria', 'kritikan', 'kritik', 'kritis',
  'kriwil', 'kriya', 'kronologi', 'kronis', 'kru', 'kruk', 'krupuk', 'kuas', 'kuasa', 'kuat', 'kuatir',
  'kubah', 'kubal', 'kubang', 'kubik', 'kubis', 'kubu', 'kubur', 'kuburan', 'kubus', 'kucai', 'kucar',
  'kucing', 'kucup', 'kuda', 'kudapan', 'kude', 'kudi', 'kudis', 'kuduk', 'kudung', 'kudus', 'kue',
  'kuil', 'kuis', 'kuit', 'kuitansi', 'kujur', 'kuku', 'kukuh', 'kukur', 'kukus', 'kuli', 'kuliah',
  'kuliahan', 'kulik', 'kulit', 'kulitnya', 'kulkas', 'kulminasi', 'kulon', 'kultural', 'kultur',
  'kulum', 'kuma', 'kuman', 'kumat', 'kumbar', 'kumis', 'kumparan', 'kumpul', 'kumpulan', 'kumuh',
  'kunci', 'kuncir', 'kuncup', 'kundalini', 'kundi', 'kungfu', 'kungkum', 'kuningan', 'kuning', 'kunjung',
  'kunjungan', 'kuno', 'kuntum', 'kunyit', 'kuorum', 'kuota', 'kuping', 'kupon', 'kupu', 'kura',
  'kurang', 'kurangan', 'kuras', 'kurator', 'kuri', 'kurikulum', 'kurir', 'kurma', 'kurnia', 'kurs',
  'kursi', 'kursus', 'kurtubi', 'kurun', 'kurung', 'kurungan', 'kusam', 'kusir', 'kusu', 'kusuma',
  'kusut', 'kuta', 'kutang', 'kutau', 'kutil', 'kutin', 'kutip', 'kutipan', 'kutub', 'kutuk', 'kutu',
];

function categorizeWords() {
  const left: string[] = [];
  const right: string[] = [];
  const mixed: string[] = [];

  for (const word of ALL_WORDS) {
    const hand = getWordHand(word);
    if (hand === 'left') left.push(word);
    else if (hand === 'right') right.push(word);
    else mixed.push(word);
  }

  return { left, right, mixed };
}

export const WORDS = categorizeWords();

export function getWords(handMode: HandMode, count: number): string[] {
  let wordPool: string[] = [];

  switch (handMode) {
    case 'left':
      wordPool = [...WORDS.left];
      break;
    case 'right':
      wordPool = [...WORDS.right];
      break;
    case 'alternating':
      const leftWords = shuffleArray([...WORDS.left]);
      const rightWords = shuffleArray([...WORDS.right]);
      const result: string[] = [];
      for (let i = 0; i < count; i++) {
        if (i % 2 === 0) {
          result.push(leftWords[i % leftWords.length]);
        } else {
          result.push(rightWords[i % rightWords.length]);
        }
      }
      return result;
    case 'both':
    default:
      wordPool = [...WORDS.left, ...WORDS.right, ...WORDS.mixed];
  }

  return shuffleArray(wordPool).slice(0, count);
}

function shuffleArray<T>(array: T[]): T[] {
  const shuffled = [...array];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}

export function getProblemWords(problemList: string[], mixRatio: number = 0.7, totalCount: number = 50): string[] {
  const problemCount = Math.floor(totalCount * mixRatio);
  const fillerCount = totalCount - problemCount;

  const problems = shuffleArray([...problemList]).slice(0, problemCount);
  const fillers = shuffleArray([...WORDS.mixed]).slice(0, fillerCount);

  return shuffleArray([...problems, ...fillers]);
}
